# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keynote Extractor site
email: johan@johanronsse.be
description: > # this means to ignore newlines until "baseurl:"
  The website for Keynote Extractor, the tool to export standard-based HTML out of Keynote documents.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keynote-extractor.com" # the base hostname & protocol for your site
twitter_username: kexftw

# Build settings
markdown: kramdown
